on:

  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env:
  REGISTRY: ${{ secrets.PRIVATE_REGISTRY }}
  IMAGE_NAME: ${{ github.event.repository.name }} + "dev"
  HUSKY_SKIP_INSTALL: 1

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: db-admin.veganhacktivists.org
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_and_push

    steps:
       - name: Deploy to Digital Ocean droplet via SSH action
         uses: appleboy/ssh-action@v0.1.3
         with:
           HOST: ${{ secrets.HOST }}
           USERNAME: ${{ secrets.USERNAME }}
           KEY: ${{ secrets.SSH_SECRET_KEY }}
           envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,COMMAND
           script: |
             docker stop $(echo $IMAGE_NAME)
             docker rm $(echo $IMAGE_NAME)
             docker run -d \
             --restart always \
             --label traefik.enable=true \
             --label traefik.docker.network=traefik-public \
             --label traefik.http.middlewares.https-redirect.redirectscheme.scheme=https \
             --label traefik.http.middlewares.https-redirect.redirectscheme.permanent=true \
             --label traefik.http.routers.app-http.middlewares=https-redirect \
             --label traefik.http.routers.app-http.rule=Host\(\`dev.veganhacktivists.org\`\) \
             --label traefik.http.routers.app-http.entrypoints=http \
             --label traefik.http.routers.app-https.rule=Host\(\`dev.veganhacktivists.org\`\) \
             --label traefik.http.routers.app-https.tls.certresolver=le \
             --label traefik.http.routers.app-https.tls=true \
             --label traefik.http.routers.app-https.entrypoints=https \
             --label traefik.http.services.app.loadbalancer.server.port=80 \
             --network=traefik-public \
             --name $(echo $IMAGE_NAME) $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
